class Album < ::ApplicationRecord
  type album_hash = {
    service_id: ::String,
    name: ::String,
    playable: bool,
    release_date: ::ActiveSupport::TimeWithZone,
    total_tracks: ::Integer,
    record_label: ::String,
    copyright: ::String,
    artwork_url: ::String,
    artwork_width: ::Integer,
    artwork_height: ::Integer,
    upc: ::String,
  }

  def self.create_by_service_id: (::String service_id) -> ::Album

  def self.create_by_service_id!: (::String service_id) -> ::Album

  def self.hash_by_service_id: (::String service_id) -> album_hash?

  def self.to_attributes: (::AppleMusic::Api::Response::album data) -> album_hash?

  def self.release_date_to_datetime: (::String release_date) -> ::ActiveSupport::TimeWithZone
end
