class Album
  def self.statuses: -> ::Hash[::String, ::Integer]
  def self.cache?: (conditions: ::Query::conditions) -> bool
  def self.generate_relation: (conditions: ::Query::conditions) -> untyped
end
