class Artist
  def self.cache?: (conditions: ::Query::conditions) -> bool
  def self.generate_relation: (conditions: ::Query::conditions) -> untyped
  def artwork_l: -> ::Artwork
  def artwork_m: -> ::Artwork
  def service_album: -> ::AppleMusicAlbum?
end
