class Artist
  def self.generate_relation: (
    conditions: ::Query::conditions
  ) -> ::Query::result
  def artwork_l: -> ::Artwork
  def artwork_m: -> ::Artwork
  def service_album: -> ::AppleMusicAlbum?
end
