class Playlist
  def self.cache?: (conditions: ::Query::conditions) -> bool
  def self.generate_relation: (
    conditions: ::Query::conditions,
    context: ::GraphQL::Query::context
  ) -> untyped
  def self.validate_author!: (::String playlist_id, ::String user_id) -> bool
  def self.validate_track_ids: (::Array[::String] track_ids) -> bool

  def add_items: (::Array[::String] track_ids) -> instance
end
