module Types
  module Objects
    class AlbumObject < BaseObject
      def instance: -> ::Album
      def apple_music_album: -> ::AppleMusicAlbum?
      def tracks: -> ::AppleMusicTrack::ActiveRecord_Associations_CollectionProxy?
    end
  end
end
