module AppleMusic
  class Client
    ENDPOINT: ::String

    VERSION: ::String

    LOCALE: ::String

    @header: ::Hash[::String, untyped]

    def get: (::String url, ?::Hash[::String, untyped] header) -> untyped
  end
end
